### ISSUE TITLE
AverageAccessTime()

### ISSUE THREAD

**Issue by bearfrieze** [coocood/freecache#1]
First and foremost, thanks for building this. I'm currently using it for [Static](https://github.com/bearfrieze/static), and so far it's been awesome.

I'm a little confused about the AverageAccessTime(). My application is logging some stats about the cache for later analysis, and I'm not sure what the return value of this function represents. My initial guess was that it is the average time it takes to fetch an object from the cache, but the number seems way to high even for nanoseconds. I have tried consulting the code but I wasn't quite able to figure it out.

Sample log from my application:

    2015/05/02 17:05:40 EntryCount: 0
    2015/05/02 17:05:40 EvacuateCount: 0
    2015/05/02 17:05:40 AverageAccessTime: 0
    2015/05/02 17:05:40 HitCount: 0
    2015/05/02 17:05:40 LookupCount: 0
    2015/05/02 17:05:40 HitRate: 0.000000

    2015/05/02 17:06:05 EntryCount: 86
    2015/05/02 17:06:05 EvacuateCount: 0
    2015/05/02 17:06:05 AverageAccessTime: 1430586343
    2015/05/02 17:06:05 HitCount: 0
    2015/05/02 17:06:05 LookupCount: 86
    2015/05/02 17:06:05 HitRate: 0.000000

    2015/05/02 17:06:15 EntryCount: 86
    2015/05/02 17:06:15 EvacuateCount: 0
    2015/05/02 17:06:15 AverageAccessTime: 1430586373
    2015/05/02 17:06:15 HitCount: 516
    2015/05/02 17:06:15 LookupCount: 602
    2015/05/02 17:06:15 HitRate: 0.857143

    2015/05/02 17:06:25 EntryCount: 86
    2015/05/02 17:06:25 EvacuateCount: 0
    2015/05/02 17:06:25 AverageAccessTime: 1430586379
    2015/05/02 17:06:25 HitCount: 1032
    2015/05/02 17:06:25 LookupCount: 1118
    2015/05/02 17:06:25 HitRate: 0.923077

**Comment by coocood** [comment]
the method name is a little bit confusing , it is actually the Unix timestamp when a entry being accessed.

**Comment by bearfrieze** [comment]
That makes sense – thanks for the quick reply. I don't think the name is that confusing now that I know. The newly added comments in the code help clear this up.

Ended up using it like this:

    log.Printf("AverageAccessTime: %d\n", cache.AverageAccessTime()-time.Now().Unix())

**Comment by coocood** [comment]
Well, this value is not used for measuring latency, it is the value that determine whether an entry can be evicted, entries has greater access time will be evacuated when it is about to be overwritten by new value.

**Comment by bearfrieze** [comment]
Yep, I got that :+1:
