### ISSUE TITLE
Possible performance enhancement

### ISSUE THREAD

**Issue by eliquious** [coocood/freecache#10]
Thanks for building this! So great! 

I have a question about the `hashFunc` and why you chose `crypto/md5`? I ran the benchmarks with a `murmur3` hash and got a substantial improvement in performance:

### Current hashFunc
```
BenchmarkCacheSet   2000000             690 ns/op
BenchmarkMapSet     2000000             828 ns/op
BenchmarkCacheGet   2000000             718 ns/op
BenchmarkMapGet     10000000            189 ns/op
BenchmarkHashFunc   5000000             253 ns/op    <- hashFunc
```

### Murmur3 hashFunc
```
BenchmarkCacheSet   3000000             480 ns/op
BenchmarkMapSet     2000000             808 ns/op
BenchmarkCacheGet   3000000             494 ns/op
BenchmarkMapGet     10000000            195 ns/op
BenchmarkHashFunc   100000000           11.0 ns/op    <- murmur3
```

Just looking for an explanation of the existing `hashFunc`.

**Comment by coocood** [comment]
I chose `crypto/md5` because it in standard library, and I didn't remember the performance difference was big like this.
Which murmur3 library did you use?

**Comment by eliquious** [comment]
I used the [gnatsd](https://github.com/nats-io/gnatsd/blob/master/hash/hash.go#L160) impementation to test with but I would probably go with [this murmur3 library](https://github.com/spaolacci/murmur3) if you were going to change the hash func. Murmur3 is really fast and also has a good distribution so it might be a good one to look at using.

**Comment by coocood** [comment]
I took a look at gnatsd implementation, it returns a uint32, but we need a uint64 hash value, maybe that's why it is much faster.

Can you test with https://github.com/spaolacci/murmur3 and post the results?

**Comment by eliquious** [comment]
Here are the results for spaolacci's implementation:

```
BenchmarkCacheSet   3000000             497 ns/op
BenchmarkMapSet     2000000             813 ns/op
BenchmarkCacheGet   3000000             521 ns/op
BenchmarkMapGet     10000000            179 ns/op
BenchmarkHashFunc   50000000            39.3 ns/op <- murmur3 64-bit
```

My `hashFunc` looks like this:

```
import "github.com/spaolacci/murmur3"

func hashFunc(data []byte) uint64 {
	return murmur3.Sum64(data)
}
```

The 64-bit version is slower but still ~6x faster than the original.

**Comment by coocood** [comment]
Thank you, the performance improvement worth adding a dependency, 

Please send a pull request to change hashfunc to spaolacci/murmur3.

**Comment by coocood** [comment]
fix by https://github.com/coocood/freecache/pull/11
