### ISSUE TITLE
NewIterator Output ExpiresAt

### ISSUE THREAD

**Issue by MarketSmart** [coocood/freecache#116]
Could you add ExpiresAt to the iterator. I'm using this with a middle man to sync cluster cache and I want to keep the expire time. Currently we are having to make an additional call to GetWithExpiration which seems kinda inefficient.

```
	//Loop through all cache entries
	cacheDump := make(map[string]map[string]string)

	iterator := c.store.NewIterator()
	for entry := iterator.Next(); entry != nil; {
		//Itterator wont give us the expiration time so we have to get it
		_, expireAt, _ := c.store.GetWithExpiration(entry.Key)

		//Add the entry to the dump
		cacheDump[string(entry.Key)] = map[string]string{
			"value": string(entry.Value),
			"ttl":   strconv.Itoa(int(expireAt)),
		}
	}
```

**Comment by xiehui3651** [comment]
I also has same need, can I slove it? @coocood

**Comment by coocood** [comment]
@xiehui3651 
It's easy to add this feature, just add an `ExpireAt` field in the `Entry` struct and in `nextForSlot` assign the value to it.
Can you send a PR for it?

**Comment by xiehui3651** [comment]
> @xiehui3651 It's easy to add this feature, just add an `ExpireAt` field in the `Entry` struct and in `nextForSlot` assign the value to it. Would you like to send a PR for it?
let me try

**Comment by xiehui3651** [comment]
#128 @coocood

**Comment by coocood** [comment]
Closed by https://github.com/coocood/freecache/pull/128
