### ISSUE TITLE
Why the GC exhausted time with freecache is almost 750 times  slower in Go 1.5 compared with 1.4

### ISSUE THREAD

**Issue by hxiaodon** [coocood/freecache#13]
I tested on my laptop MacBook Pro with Intel i7 2.5GHZ 16GB memory

Go 1.5.3's result
GC pause with free cache: 75.955282ms
GC pause with map cache: 513.058607ms

Go 1.4.3's result
GC pause with free cache: 112.353µs
GC pause with map cache: 237.954365ms

As official specification, the GC problem should be better in Go's higher version.

**Comment by coocood** [comment]
Please provide the test code.

And for Go 1.5 and above, explicitly call runtime.GC() will force stop the world, which normally doesn't happen in  real life.

**Comment by hxiaodon** [comment]
Test code is yours in README.md
https://github.com/coocood/freecache#about-gc-pause-issue
