### ISSUE TITLE
Peek() returns expired values

### ISSUE THREAD

**Issue by pflanagan-cs** [coocood/freecache#132]
I assumed `Peek()` would return same result as `Get()`, just without modifying access time or counters
But expiry time is not checked by Peek() at all so it will return expired entries if they are found.

`Peek()` function description `Peek returns the value or not found error, without updating access time or counters.` does not mention that expiry check is not done and an expired value may be returned without error

Peek() should honour the expiry time, or the description needs to warn about this behaviour

**Comment by coocood** [comment]
Yes, the document needs updates, would you like to send a PR to fix it?

**Comment by pflanagan-cs** [comment]
Created PR #133
