### ISSUE TITLE
Set失败 没有反馈

### ISSUE THREAD

**Issue by ziyebuboka** [coocood/freecache#23]
package main

import (
	_ "errors"
	"fmt"
	"runtime/debug"
	_ "strconv"
	"strings"

	"github.com/coocood/freecache"
)

var kvMap map[string]string

func main() {

	debug.SetGCPercent(10)
	cache := freecache.NewCache(10240 * 1024)
	kvMap = make(map[string]string)
	for i := 0; i <= 10000; i++ {
		key := fmt.Sprintf("key%v", i)
		value := strings.Repeat(key, 1000)

		if _, ok := kvMap[key]; ok {
			continue
		}

		kvMap[key] = value

		keyBt := []byte(key)

		valueBt := []byte(value)

		err := cache.Set(keyBt, valueBt, 0)
		if err != nil {
			fmt.Println("set error:", err)
			fmt.Println("key len:", len(key))
			fmt.Println("keyBt len:", len(keyBt))
		}

	}

	bErr := false
	errNum := 0

	for k, v := range kvMap {
		keyBt := []byte(k)
		valueBt, err := cache.Get(keyBt)
		if err != nil {
			errNum++
			bErr = true
		} else {
			value := string(valueBt[:])
			if strings.Compare(v, value) != 0 {
				fmt.Println("value compare error")
				bErr = true
			}
		}

	}

	fmt.Println("bErr:", bErr, errNum)
	fmt.Println("value compare end-----------------------------")

	fmt.Printf("hit rate is %v, evacuates %v, entries %v, average time %v, expire count %v\n",
		cache.HitRate(), cache.EvacuateCount(), cache.EntryCount(), cache.AverageAccessTime(), cache.ExpiredCount())

	cache.ResetStatistics()
	fmt.Printf("hit rate is %v, evacuates %v, entries %v, average time %v, expire count %v\n",
		cache.HitRate(), cache.EvacuateCount(), cache.EntryCount(), cache.AverageAccessTime(), cache.ExpiredCount())

}

上面是我的测试代码，set数据到freecache里，但是get的时候就有很多的value是得不到的，应该是set失败了吧，但是没有error回馈啊

**Comment by coocood** [comment]
The data size is larger than the capacity 10MB, so many entries is evicted.

**Comment by ziyebuboka** [comment]
失败了 但是没有反馈啊 没有error 这样无法得知是否set进去了  现网使用的话 就得先set 再get一下来判断么？

**Comment by ziyebuboka** [comment]
有qq么，可否加一下

**Comment by coocood** [comment]
When you set a new value is always succeed, the evicted value is the value you set a long time ago.

**Comment by coocood** [comment]
key0 may be evicted when you set key 10000.

**Comment by ziyebuboka** [comment]
明白了，是属于热数据型自动淘汰的特性

**Comment by ziyebuboka** [comment]
非常感谢
