### ISSUE TITLE
runtime error on i386

### ISSUE THREAD

**Issue by negbie** [coocood/freecache#36]
Hi,

before the latest commits freecache could be used on i386. That was possible because 

atomic.AddInt64
atomic.LoadInt64

was only used to set and get the counters for the stats. So when none of the stats method were used it was able to use it on i386. But since we use atomic.AddInt64 inside the get and set (segment.go) method freecache isn't useable on i386 anymore.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb74ec87c]

goroutine 1 [running]:
sync/atomic.AddUint64(0x97636cb4, 0x1, 0x0, 0x1, 0x79eb3042)
	/usr/lib/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/coocood/freecache.(*segment).get(0x97636c88, 0x9bfd802a, 0x22e, 0x22e, 0x3042c69e, 0x65250c3f, 0x87234088, 0x0, 0xb7955b80, 0x9bfce000, ...)
	/go/src/github.com/coocood/freecache/segment.go:201 +0x44a
github.com/coocood/freecache.(*Cache).Get(0x9760a000, 0x9bfd802a, 0x22e, 0x22e, 0x0, 0x97484188, 0x4, 0x9bfca000, 0x0)
	/go/src/github.com/coocood/freecache/cache.go:56 +0xaa

**Comment by negbie** [comment]
sync/atomic expects the first word in an allocated struct to be 64-bit
aligned on both ARM and x86-32. See https://goo.gl/zW7dgq for more details.

**Comment by coocood** [comment]
Fixed by https://github.com/coocood/freecache/pull/38
