### ISSUE TITLE
panic in processor: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by ydf** [coocood/freecache#48]
runtime/debug.Stack(0xcc477985d0, 0xa486a0, 0xe418e0)
    /opt/go/src/runtime/debug/stack.go:24 +0xa7
git.apache.org/thrift.git/lib/go/thrift.(*TSimpleServer).processRequests.func1()
    /src/git.apache.org/thrift.git/lib/go/thrift/simple_server.go:186 +0x5a
panic(0xa486a0, 0xe418e0)
    /opt/go/src/runtime/panic.go:491 +0x283
github.com/coocood/freecache.(*RingBuf).EqualAt(0xc42028c0d8, 0xcc3850dad0, 0x28, 0x20, 0x347fffde, 0x7f47246617c0)
    /src/github.com/coocood/freecache/ringbuf.go:147 +0x1de

**Comment by coocood** [comment]
Thank you for your report.
Is it the full stack?
How the cache is used? 
Is it reproducible?

**Comment by ydf** [comment]
panic in processor: runtime error: slice bounds out of range: goroutine [running]:
runtime/debug.Stack(0xcc477985d0, 0xa486a0, 0xe418e0)
    /opt/go/src/runtime/debug/stack.go:24 +0xa7
git.apache.org/thrift.git/lib/go/thrift.(*TSimpleServer).processRequests.func1()
    /src/git.apache.org/thrift.git/lib/go/thrift/simple_server.go:186 +0x5a
panic(0xa486a0, 0xe418e0)
    /opt/go/src/runtime/panic.go:491 +0x283
github.com/coocood/freecache.(*RingBuf).EqualAt(0xc42028c0d8, 0xcc3850dad0, 0x28, 0x20, 0x347fffde, 0x7f47246617c0)
    /src/github.com/coocood/freecache/ringbuf.go:147 +0x1de
github.com/coocood/freecache.(*segment).lookup(0xc42028c0d8, 0xcbdc287c00, 0x13, 0x40, 0xcc38501e9a, 0xcc3850dad0, 0x28, 0x20, 0xc420084400, 0x7f472e9ae438)
    /src/github.com/coocood/freecache/segment.go:346 +0xff
github.com/coocood/freecache.(*segment).get(0xc42028c0d8, 0xcc3850dad0, 0x28, 0x20, 0x5635ef0c1e9a47ef, 0xb18582, 0x9, 0xcc477988c0, 0x2, 0x2, ...)
    /src/github.com/coocood/freecache/segment.go:199 +0x118
github.com/coocood/freecache.(*Cache).Get(0xc420246000, 0xcc3850dad0, 0x28, 0x20, 0x28, 0x30, 0xcc384f9560, 0x7f46d00261c8, 0xcc477989d8)
    /src/github.com/coocood/freecache/cache.go:56 +0xe1  
main.(*RpcServiceImpl).GetCache(0xc4201fa220, 0xcc4de8d420, 0x1, 0x1, 0x2f8, 0xcc00c4d850, 0x9, 0x1, 0x0, 0x0, ...)
    /src/handler.go:108 +0x150   
this  line code（ val, err := this.cache.Get(StringBytes(key))）



Cache := freecache.NewCache(config.CacheGB * 1024 * 1024 * 1024)
QueryCache := freecache.NewCache(3 * 1024 * 1024)
handler := &RpcServiceImpl{}
handler.cache = Cache


 Is it reproducible? 
生产环境跑了半个月， 复现不了

**Comment by coocood** [comment]
@ydf 
Would you please try this branch https://github.com/coocood/freecache/tree/assert
I added an assert and prints some helpful message.
If the panic occurs again, the message would make debugging easier.
Thank you!

**Comment by ydf** [comment]
不行 还是 出现这个错误。  debug  没有信息

**Comment by ydf** [comment]
is_ok := firstLen >= 0 && firstLen <= len(p) && readOff >= 0 && readOff <= len(rb.data)
		assertF(is_ok,
			"firstLen:%d pLen:%d readOff:%d dataLen:%d", firstLen, len(p), readOff, len(rb.data))

func assertF(v bool, fmtStr string, args ...interface{}) {
	if !v {
		msg := fmt.Sprintf(fmtStr, args...)
		fmt.Println(msg)
	}
}

**Comment by coocood** [comment]
@ydf 
Are you sure the binary is the `assert` branch?
Has the line number of the panic stack changed?

**Comment by ydf** [comment]
![882c0326-31fb-4d8f-bd4b-c4c4ec1f2964](https://user-images.githubusercontent.com/4960943/50224831-da7e2f00-03d9-11e9-88af-3da9ce424d68.png)

error log
```
2018/12/19 20:50:56 panic in processor: runtime error: slice bounds out of range: goroutine 69 [running]:
runtime/debug.Stack(0xcba1341f68, 0x6e7ea0, 0x8e02f0)
    /opt/go/src/runtime/debug/stack.go:24 +0xa7
git.apache.org/thrift.git/lib/go/thrift.(*TSimpleServer).processRequests.func1()
    /opt/src/git.apache.org/thrift.git/lib/go/thrift/simple_server.go:186 +0x5a
panic(0x6e7ea0, 0x8e02f0)
    /opt/go/src/runtime/panic.go:491 +0x283
github.com/coocood/freecache.(*RingBuf).EqualAt(0xc420141670, 0xcba915c540, 0x12, 0x0, 0x3bffffb, 0x411f17)
    /opt/src/github.com/coocood/freecache/ringbuf.go:153 +0x3f1
github.com/coocood/freecache.(*segment).lookup(0xc420141670, 0xcc3e9c2000, 0x47, 0x80, 0xcc6a0e2fba, 0xcba915c540, 0x12, 0x0, 0x461ac0, 0xc423ddbc00)
    /opt/src/github.com/coocood/freecache/segment.go:346 +0xff
github.com/coocood/freecache.(*segment).get(0xc420141670, 0xcba915c540, 0x12, 0x0, 0x488bf9972fba5c16, 0x697cdd, 0x744a6f, 0x9, 0xcba13422d0, 0x2, ...)
    /opt/src/github.com/coocood/freecache/segment.go:199 +0x118
github.com/coocood/freecache.(*Cache).GetWithExpiration(0xc42013a000, 0xcba915c540, 0x12, 0x0, 0x12, 0x3, 0x4, 0x3, 0x0, 0x0)
    /opt/src/github.com/coocood/freecache/cache.go:73 +0xe5
main.(*RpcServiceImpl).GetCache(0xcba0b36120, 0xcbee320780, 0x8, 0x8, 0x14, 0xcbfec64fd8, 0x8, 0x20, 0x0, 0x0, ...)
    /opt/src/handler.go:109 +0x16b
main.(*RpcServiceImpl).Get(0xcba0b36120, 0x8b7280, 0xc4200120b0, 0xcc295b55e0, 0x66, 0x66, 0x0, 0x0, 0x0, 0x0, ...)
    /opt/src/handler.go:163 +0x366
pdb.(*pdbServerProcessorGet).Process(0xcba0b340f0, 0x8b7280, 0xc4200120b0, 0x935179, 0x8bc3a0, 0xcba0b6c7e0, 0x8bc3a0, 0xcba0b6c870, 0xcba0b68601, 0x0, ...)
    /opt/src/pdb/pdb.go:159 +0x2d2
pdb.(*PdbServerProcessor).Process(0xcba0b36180, 0x8b7280, 0xc4200120b0, 0x8bc3a0, 0xcba0b6c7e0, 0x8bc3a0, 0xcba0b6c870, 0xc42012a401, 0x0, 0x0)
    /opt/src/pdb/pdb.go:126 +0x336
git.apache.org/thrift.git/lib/go/thrift.(*TSimpleServer).processRequests(0xcba0b52000, 0x8b8a60, 0xcba0b28390, 0x0, 0x0)
    /opt/src/git.apache.org/thrift.git/lib/go/thrift/simple_server.go:201 +0x28c
git.apache.org/thrift.git/lib/go/thrift.(*TSimpleServer).AcceptLoop.func1(0xcba0b52000, 0x8b8a60, 0xcba0b28390)
    /opt/src/git.apache.org/thrift.git/lib/go/thrift/simple_server.go:142 +0x73
created by git.apache.org/thrift.git/lib/go/thrift.(*TSimpleServer).AcceptLoop
    /opt/src/git.apache.org/thrift.git/lib/go/thrift/simple_server.go:140 +0xfa
2018/12/19 21:10:21 error processing request: Incorrect frame size (218762506)
2018/12/19 21:10:25 error processing request: Incorrect frame size (1936089459)
```

**Comment by coocood** [comment]
This time is panicked on a different line, the original line is not panicked this time.
Would you add another similar assert before the second panic and run again?

**Comment by ydf** [comment]
ok

**Comment by ydf** [comment]
func StringBytes(s string) []byte {
	return *(*[]byte)(unsafe.Pointer(&s))
}

I  use  this  function  string  to  bytes  for  cache  key， it's safe and ok？

**Comment by coocood** [comment]
No, the conversion is incorrect.
You should do it this way:

https://github.com/pingcap/tidb/blob/master/util/hack/hack.go#L36

**Comment by ydf** [comment]
thank u
