### ISSUE TITLE
GC settings

### ISSUE THREAD

**Issue by alehano** [coocood/freecache#5]
Hi. Thanks for the project. I have a question. I don't much understand managing GC. So, if I want to allocate 10 gb of RAM for cache (on a machine with 16 gb RAM), what value of debug.SetGCPercent() would be? And what will happen if I don't set GCPercent at all?

**Comment by coocood** [comment]
If you set GC percent to be 10%, then your application could consume 11GB memory before GC.
If you don't set it, your machine will run out of memory.
