### ISSUE TITLE
Keys are case insensitive

### ISSUE THREAD

**Issue by mvasi90** [coocood/freecache#50]
Why keys are case insensitive?
I'm storing random string as bytes to use as session hash.

Using it as session hash is dangerous

**Comment by coocood** [comment]
It's not case insensitive.

**Comment by mvasi90** [comment]
Then it's a bug.
I'm changing to lowercase any character and it works correctly.

**Comment by coocood** [comment]
Would you please write a test case to reproduce this issue?
I wrote a test case but didn't reproduce it.

**Comment by mvasi90** [comment]
Wait a moment please, I'm testing since I wrote the last message.
Don't waste your time, maybe I'm wrong.

**Comment by coocood** [comment]
That's OK.
