### ISSUE TITLE
No benchmark for concurrent performance

### ISSUE THREAD

**Issue by manishrjain** [coocood/freecache#54]
I was expecting that the cache benchmarks would also test for concurrent performance of the cache. But, didn't see that in cache_test.go.

**Comment by coocood** [comment]
I'm going to remove the memory allocation of `Get` by adding a parameter `buf []byte`. 
I can add concurrent benchmarks after this optimization.

**Comment by coocood** [comment]
Fixed by https://github.com/coocood/freecache/pull/58
