### ISSUE TITLE
Question about lookupByOff in delEntryPtr

### ISSUE THREAD

**Issue by pingworld** [coocood/freecache#55]
Thanks for your repo.

I feel confused when I read the del func of segment. Why there is another lookupByOff in delEntryPtr while you have been got the idx by lookup. I have checked the codes carefully, but I still can't find out they can return the different values. 

I want to know If there is other consideration for checking it again to assure safty.

Any reply would be appreciated.

**Comment by coocood** [comment]
@pingworld 
I read the code again and find out that the second lookup can be avoided.
I will push a commit soon.
Good catch, thank you!
