### ISSUE TITLE
ringbuf.Evacuate

### ISSUE THREAD

**Issue by codergma** [coocood/freecache#59]
https://github.com/coocood/freecache/blob/e028aa6853e7c978b34abbdfbf47c1b95025b88d/ringbuf.go#L190
This line is aways false. Because:
1. rb.index < readOff       => rb.index+length  <readEnd
2. readEnd<=len(rb.data) => rb.index+length <len(rb.data)
3. n<=length                     => rb.index+n < llen(rb.data)

**Comment by coocood** [comment]
Good catch!
Would you please send a PR for it?

**Comment by codergma** [comment]
yes
