### ISSUE TITLE
How catch eviction by size

### ISSUE THREAD

**Issue by recoilme** [coocood/freecache#63]
Hello @coocood !
I want to catch a deleted key when there is not enough memory(space), and move it to another repository (in file - https://github.com/recoilme/pudge)
May you please tell me how to do it right?
Something like this https://godoc.org/github.com/allegro/bigcache#Config.OnRemoveFilterSet
Thank you

**Comment by coocood** [comment]
I'm afraid there is no easy way to do it.

**Comment by recoilme** [comment]
Thank you for fast response!
