### ISSUE TITLE
Memory continuously consumed by (*segment).expand()?

### ISSUE THREAD

**Issue by bschofield** [coocood/freecache#66]
Hi,

I have a long-running application which uses _freecache_ together with a fairly large number (250,000) of goroutines. The application is running on a 16GB machine, and 8GB of that is given over to _freecache_ caches. I have GOGC set to 50, and it seems (from checking the allocated object sizes using pprof) that garbage collection is working adequately.

The issue I have is that the amount of memory allocated by `(*segment).expand()` continuously increases over time. When the application has been running only a few minutes, the profile of top consumers as reported by `go tool pprof` (against an _inuse_space_ heap profile) looks like this:

```
(pprof) top20
Showing nodes accounting for 8339.11MB, 99.25% of 8402.05MB total
Dropped 46 nodes (cum <= 42.01MB)
      flat  flat%   sum%        cum   cum%
    8192MB 97.50% 97.50%     8192MB 97.50%  github.com/coocood/freecache.NewRingBuf
   94.53MB  1.13% 98.63%    94.53MB  1.13%  runtime.malg
      31MB  0.37% 98.99%    68.76MB  0.82%  my-app/worker.(*Pool).worker
   19.08MB  0.23% 99.22%  8213.07MB 97.75%  my-app/worker.NewPool
    1.99MB 0.024% 99.24%  8193.99MB 97.52%  github.com/coocood/freecache.NewCache
    0.50MB 0.006% 99.25%  8213.57MB 97.76%  main.main
         0     0% 99.25%  8193.99MB 97.52%  my-app/foo.NewFoo
         0     0% 99.25%     8192MB 97.50%  github.com/coocood/freecache.newSegment
         0     0% 99.25%  8213.57MB 97.76%  runtime.main
         0     0% 99.25%    96.82MB  1.15%  runtime.mstart
         0     0% 99.25%    96.82MB  1.15%  runtime.newproc.func1
         0     0% 99.25%    96.82MB  1.15%  runtime.newproc1
         0     0% 99.25%    96.82MB  1.15%  runtime.systemstack
```

After a day or so of runtime, it looks like this:

```
(pprof) top20
Showing nodes accounting for 8969.93MB, 99.41% of 9023.42MB total
Dropped 42 nodes (cum <= 45.12MB)
Showing top 20 nodes out of 21
      flat  flat%   sum%        cum   cum%
    8192MB 90.79% 90.79%     8192MB 90.79%  github.com/coocood/freecache.NewRingBuf
  658.83MB  7.30% 98.09%   658.83MB  7.30%  github.com/coocood/freecache.(*segment).expand
   94.53MB  1.05% 99.13%    94.53MB  1.05%  runtime.malg
   19.08MB  0.21% 99.35%  8213.07MB 91.02%  my-app/worker.NewPool
       3MB 0.033% 99.38%   689.63MB  7.64%  my-app/worker.(*Pool).worker
    1.99MB 0.022% 99.40%  8193.99MB 90.81%  github.com/coocood/freecache.NewCache
    0.50MB 0.0055% 99.41%   686.13MB  7.60%  my-app/foo.(*Foo).foo
         0     0% 99.41%   686.63MB  7.61%  my-app/foo.(*Foo).FooBar
         0     0% 99.41%   511.37MB  5.67%  my-app/foo.(*Foo).setBaz
         0     0% 99.41%   137.63MB  1.53%  my-app/foo.(*Foo).setQuux
         0     0% 99.41%  8193.99MB 90.81%  my-app/foo.NewFoo
         0     0% 99.41%   658.83MB  7.30%  github.com/coocood/freecache.(*Cache).Set
         0     0% 99.41%   658.83MB  7.30%  github.com/coocood/freecache.(*segment).insertEntryPtr
         0     0% 99.41%   658.83MB  7.30%  github.com/coocood/freecache.(*segment).set
         0     0% 99.41%     8192MB 90.79%  github.com/coocood/freecache.newSegment
         0     0% 99.41%  8213.07MB 91.02%  main.main
         0     0% 99.41%  8213.07MB 91.02%  runtime.main
         0     0% 99.41%    96.82MB  1.07%  runtime.mstart
         0     0% 99.41%    96.82MB  1.07%  runtime.newproc.func1
         0     0% 99.41%    96.82MB  1.07%  runtime.newproc1
```

-- so an increase of several hundred MB in `github.com/coocood/freecache.(*segment).expand`.

After a few days, the app runs out of memory and the OOM killer ends it. I very strongly suspect that this is due to the growth in `(*segment).expand`, simply because I can't see anything else growing or leaking over time.

My question is: Is this memory growth expected? If so, is there any way to limit or bound it?

**Comment by coocood** [comment]
Does the number of entries `cache.EntryCount()` grows over time?

**Comment by bschofield** [comment]
Yes. There are actually three caches in this application. Two of them top out, but one of them seems to be growing approximately linearly:

![cache](https://user-images.githubusercontent.com/1534502/69965396-17b8cf80-150c-11ea-8f01-a65166f40899.png)

At the end of that ~40 hours runtime, the memory allocated by `(*segment).expand()` has grown to >1GB, with everything else the same:

```
      flat  flat%   sum%        cum   cum%
    8192MB 85.84% 85.84%     8192MB 85.84%  github.com/coocood/freecache.NewRingBuf
 1172.36MB 12.28% 98.12%  1172.36MB 12.28%  github.com/coocood/freecache.(*segment).expand
   94.53MB  0.99% 99.11%    94.53MB  0.99%  runtime.malg
...
```

**Comment by coocood** [comment]
Yes, small objects require more memory when the cache is fully filled.
Please use a smaller cache and see if the `expand` still keep growing and reach 25% of `NewRingBuf`.

**Comment by bschofield** [comment]
Thanks very much for your help with this. Now that I understand the behaviour, all is fine.

The only suggestion that I would make is that it might be sensible to put something in the documentation explaining that for very small keys, up to 125% of the amount of memory assigned to the cache might be consumed, so that other people are not caught out in the same way.

**Comment by mr-tcx** [comment]
what is reason from OOM of application, although up to 125%  of the cache。 my means is 8 * 1.25 = 10GB < 16GB
