### ISSUE TITLE
Possibility to retrieve entire cache data(keys and its values)

### ISSUE THREAD

**Issue by ksudheernathreddy** [coocood/freecache#68]
Hi, 
 
  I would like to know is there any way to dump entire data from cache?
  For example:
  data, err := cache.GetAll()
  
  Thanks in advance

**Comment by coocood** [comment]
Use `Iterator` and call `Next` until nil can retrieve all cache data.

**Comment by ksudheernathreddy** [comment]
Thanks, it works :)
