### ISSUE TITLE
Poor cache space utilization with "sequential" keys / multithreaded

### ISSUE THREAD

**Issue by anton-povarov** [coocood/freecache#7]
inserting 1 million consecutive keys into 1Mb sized cache gives something like this
code (sorry, messy): https://gist.github.com/anton-povarov/90740565548bd5c0517c
```
entries: 4672, evacuated: 0, overwritten: 0
avg_value_len: 16
bytes per item: 224.43835616438355 - 16 - 16 = 192.43835616438355
```
so we could only insert 4672 keys into 1megabyte cache, which is ~224 bytes per item, subtracting 16 byte key len, 16 byte value len, we're left wih ~192 bytes of overhead per key (of which 24 are occupied by header).

My suspicion was that this is due to fnva hash failing to give well distributed values for these very regular keys. Which leads to poor segments utilization.

So i've changed the hashing function to md5 for a quick and dirty test, like this
```
func fnvaHash(data []byte) uint64 {
	sum := md5.Sum(data)
	return binary.LittleEndian.Uint64(sum[:8])

	// var hash uint64 = 14695981039346656037
	// for _, c := range data {
	// 	hash ^= uint64(c)
	// 	hash *= 1099511628211
	// }
	// return hash
}
```

which gives the following result
```
entries: 12409, evacuated: 0, overwritten: 0
avg_value_len: 43.480773
bytes per item: 84.50124909339995 - 43.480773 - 16 = 25.02047609339995
```

which seems much much better for basically the same code.

What i suggest is to find/implement a better hash function (like murmur3 or something), maybe this one: https://github.com/spaolacci/murmur3

**Comment by anton-povarov** [comment]
tested with https://github.com/spaolacci/murmur3

result
```
entries: 12417, evacuated: 0, overwritten: 0
avg_value_len: 43.480773
bytes per item: 84.44680679713296 - 43.480773 - 16 = 24.966033797132965
```

and is about (non-scientifically) 20% faster than md5

**Comment by anton-povarov** [comment]
Hm... actually tested it some more. And while a better hash function does solve the issue in single-threaded case, it's still very bad in multithreaded case.
With 10 goroutines, all inserting same keys, but slightly different values (so a zillion of evacuates happens) - overhead per item still grows to ridiculous values.

for example:
same code as above gist, but changed the following params
```
const cache_size = 10 * 1024 * 1024 // was 1 megabyte
n_keys := 10 * 1000 * 1000 // was 1 million
```

here's the result with: const n_routines = 10
```
entries: 42078, evacuated: 120957842, overwritten: 77988935
avg_value_len: 43.49973858
bytes per item: 249.1981558058843 - 43.49973858 - 16 = 189.69841722588433
```

vs const n_routines = 1
```
entries: 125323, evacuated: 0, overwritten: 0
avg_value_len: 43.4929523
bytes per item: 83.6698770377345 - 43.4929523 - 16 = 24.176924737734495
```

**Comment by coocood** [comment]
Thank you for your intensive testing on it.
So it seems like the memory utilization issue is not caused by hash function.
The difference of entry overhead seems too big for the difference of hash function distribution quality.

**Comment by coocood** [comment]
I think this is normal.

If you set n_routines to one, then every key is new, there is no overwrites, the entry length is exactly (24+keyLen+valueLen).

If you set n_routines to 10, the entry can be overwritten. 

If the new value is larger than the old entry's capacity, it won't be updated in place, then the old entry's space is not utilized. 

If the new value is smaller than the old entry's capacity, then there would be an in-place update, (capacity - valueLen) of space is not utilized.

Whenever the capacity is smaller than the new value, the capacity is doubled, so when you keep increasing the size of the new value, it won't keep writing new entries, most of the update would be in place update.

**Comment by anton-povarov** [comment]
Even in single threaded case with fnvhash utilization is poor. With zero overwrites/evictions.

**Comment by coocood** [comment]
I will try to find the answer tomorrow, you can print out every segment's entry count to see how it is distributed .

**Comment by anton-povarov** [comment]
hacked it together for 1 mil items, 1 goroutine, 1 meg cache
data gathered with
```
		n := atomic.LoadInt64(&cache.segments[i].entryCount)
		fmt.Printf("%d %d\n", i, n)
```

fnvhash
```
antoxa@antoxa-suse:~/_Dev/go/src/antoxa> cat 1.txt | awk '{ print $2 }' | sort -n | uniq -c
    384 0
      2 470
      4 479
      6 480
      4 481
      2 482
     10 483
      2 484
      6 485
      4 486
      6 487
     14 488
     12 489
      6 490
     12 491
      2 492
      8 494
      4 495
      4 496
      6 497
      4 499
      4 501
      4 503
      2 508
```

murmur3
```
antoxa@antoxa-suse:~/_Dev/go/src/antoxa> cat 1.txt | awk '{ print $2 }' | sort -n | uniq -c
      4 471
      2 473
      2 475
      6 477
      8 478
     12 479
     12 480
     20 481
      6 482
     26 483
     14 484
     20 485
     24 486
     24 487
     18 488
     40 489
     30 490
     24 491
     18 492
     44 493
     44 494
     18 495
     18 496
     14 497
     20 498
     10 499
     12 500
      2 501
     10 502
      4 503
      2 504
      2 505
      2 508

**Comment by coocood** [comment]
Thank you for the great work to address this issue.  The hash function definitely need to change.

**Comment by coocood** [comment]
Changed to MD5 in the latest commit 28070c015675a739b0ed7b5099d4f55064b57ce7
