### ISSUE TITLE
有一点小问题想请教一下

### ISSUE THREAD

**Issue by zhaohailin111** [coocood/freecache#77]
1、请问这个consecutiveEvacuate值大于多少被淘汰是基于什么原理？
https://github.com/coocood/freecache/blob/e96d57d8c3ff6e42dfe3a7e65b441c28f9109b3e/segment.go#L183

2、请问这里更换成256个切片expand()时是否会表现的更好？
https://github.com/coocood/freecache/blob/e96d57d8c3ff6e42dfe3a7e65b441c28f9109b3e/segment.go#L62

**Comment by Mutated1994** [comment]
我也提了一个issue关于set的时候为什么要将len(rb.data)/4，我猜这里跟我提的issue是有关联的。
1. 因为set的时候保证了一组kv+head不会大于len(rb.data)/4，那么在淘汰的时候如果连续5个都没有清理出空间，很有可能会造成短时间内的无限循环（假设里面只有4组，而且每组kv+head=len(rb.data)/4）。
2. 如果rb里面碎片在比较后面的话，Evacuate过程会比较费时。
总结：首先确保不会hang住，才会加`consecutiveEvacuate > 5`这个逻辑，其次牺牲掉一些hit率，换取set的高效。这两点也只是我个人猜测，大牛们勿喷。
