### ISSUE TITLE
consider jonhoo/drwmutex instead sync.Mutex

### ISSUE THREAD

**Issue by kron4eg** [coocood/freecache#8]
https://github.com/jonhoo/drwmutex is claimed to have much lower lock retention time on multicore linux_amd64 systems (with automatic fallback to sync.RWMutext)

@coocood what do you think about that?

**Comment by coocood** [comment]
That is Interesting, but `drwmutex` is supposed to replace `sync.RWMutex`, not `sync.Mutex`.

**Comment by kron4eg** [comment]
Yes, indeed it's imitating sync.RWMutex, so you could use it too instead of sync.Mutex

**Comment by coocood** [comment]
But `drwmutex` is optimised for `RLock` method and `freecache` only use `Lock` method.

**Comment by kron4eg** [comment]
here https://github.com/coocood/freecache/blob/master/cache.go#L53 `RLock` could be used since it's only reading, unless of course there are no writes behind the scene.

Anyway, if you feel so please close this ticket.

**Comment by coocood** [comment]
It is not read only, the access time for the entry is updated when you get it.
