### ISSUE TITLE
[Questions & Feedback] Update value without changin expiration

### ISSUE THREAD

**Issue by dikkini** [coocood/freecache#81]
Hi!

Cool project, very fast. 
I choose this instead of bigcache for one reason: bigcache hasn't expire for cache entry, only for entire cache.

Cons: not enough examples how to work with cache

Questions:
1. How to update entry in cache and do not update expire time?
2. How to see current expire time for entry?

**Comment by coocood** [comment]
There is a `TTL` method returns the `timeLeft`, which is `expireTime - currentTime`.
Or you can use `GetWithExpiration` that returns the expire time.

Then you can use the previous retrieved expire time to update the entry.

**Comment by dikkini** [comment]
works like a charm.

ty
