### ISSUE TITLE
Is there any difference between Get method and GetWithExpiration

### ISSUE THREAD

**Issue by kooksee** [coocood/freecache#82]
I stored the cache, but I still want the expired data, and now I find that the GetWithExpiration method does not meet my requirements, and I find that its implementation is the same as the Get method, so I am confused

**Comment by coocood** [comment]
Currently, there is no way to get the expired data.
If you still need the data, why set it to expire?

**Comment by kooksee** [comment]
`Peek` function can meet my requirements。
I want to calculate the real BufSize
