### ISSUE TITLE
Clear method without doubling of memory

### ISSUE THREAD

**Issue by Staon** [coocood/freecache#95]
Hello,

we have a problem with the Clear method. Sometimes we need to clean the cache. However, the Clear method replaces the RingBuffers by new ones. That causes doubling of process's memory as both old and new blocks are present at the same time until the garbage collector frees them.

Is it possible to implement the Clear method without memory doubling? IMHO, just reset of the _begin_ and _end_ pointers of existing RingBuffers should be appropriate.

Best regards.
Ondra

**Comment by coocood** [comment]
Good idea!
Would like to send a PR for this improvement?

**Comment by Staon** [comment]
The PR is here: #96
